version: '3'
services:
  grafana:
    build: .
    image: gsa/grafana:0.2.0
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=<user>
      - GF_SECURITY_ADMIN_PASSWORD=<user>
      - GF_INSTALL_PLUGINS=grafana-googlesheets-datasource,marcusolsson-csv-datasource,grafana-clock-panel,marcusolsson-calendar-panel,mxswat-separator-panel,marcusolsson-json-datasource
      - BASIC_AUTH_PASSWORD=<bridge-password>
      - KDRIVE_FILE_ID=<file-id>
      - KDRIVE_BRIDGE_HOST=<bridge-host>
      - BASIC_AUTH_USER=<bridge-user>
      - TZ=<tz>
