version: '3'
services:
  grafana:
    build: .
    image: gsa/grafana:0.2.0
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=<user>
      - GF_SECURITY_ADMIN_PASSWORD=<password>
      - GF_INSTALL_PLUGINS=grafana-googlesheets-datasource,marcusolsson-csv-datasource,grafana-clock-panel,marcusolsson-calendar-panel,mxswat-separator-panel,marcusolsson-json-datasource
      - BASIC_AUTH_PASSWORD=<password>o
      - CALENDAR_KDRIVE_FILE_ID=<file-id>
      - ANNOTATIONS_KDRIVE_FILE_ID=<file-id>
      - KDRIVE_BRIDGE_HOST=<host>
      - BASIC_AUTH_USER=<user>
      - TZ=<tz>
